### ISSUE TITLE
Regarding Bilateral Prompt

### ISSUE THREAD

**Issue by NatureExplorer24** [fawnliu/TRIS#5]
Thanks authors for sharing the code. I have a following question:

When computing the attention map for visual features, is Av in the below line a all-one tensor? Only one language vector is used as key and the softmax is applied on the last dimension which is 1. 

https://github.com/fawnliu/TRIS/blob/b45f660783b0334f6110c3afe7d53c8b30eab418/model/attn.py#L122

**Comment by fawnliu** [comment]
Sorry for the late. You can test it by summarizing its value on the corresponding dimension.
