### ISSUE TITLE
`demo.py` img_size hardcoded to incorrect value

### ISSUE THREAD

**Issue by ThereforeGames** [fawnliu/TRIS#6]
Hi,

Thank you for sharing your work!

I noticed in `demo.py`, the `get_transform()` method does not respect the `size` argument. It is hardcoded to resize to (224,224):

https://github.com/fawnliu/TRIS/blob/b45f660783b0334f6110c3afe7d53c8b30eab418/demo.py#L22

I believe this should be `(size,size)`, which will take 320px by default. I can confirm that this change results in a heatmap that is a lot closer to the example in your readme.

---

## Before fix

![heatmap](https://github.com/fawnliu/TRIS/assets/95403634/dcd05b46-f3ed-48d7-94db-1595d4e9d075)

## After fix

![heatmap_fixed](https://github.com/fawnliu/TRIS/assets/95403634/baeaf124-28f2-4e09-8013-d02208372521)

I'm still not sure why my heatmap doesn't match your example 100%, but the results are impressive nonetheless. 🙂

**Comment by fawnliu** [comment]
Thanks for your suggestion. I updated this typo.
