### ISSUE TITLE
No such file or directory: '../output/refcocog_umd/refcocog_train_names.json'

### ISSUE THREAD

**Issue by RDXiaoLu** [fawnliu/TRIS#7]
run in the order you specified but run these code :

Train IRNet and generate pseudo masks.
cd IRNet

dir=../output
CUDA_VISIBLE_DEVICES=0,1,2,3 python run_sample_refer.py   --cam_out_dir $dir/refcocog_umd/cam   --ir_label_out_dir $dir/refcocog_umd/ir_label   --ins_seg_out_dir $dir/refcocog_umd/ins_seg   --train_list $dir/refcocog_umd/refcocog_train_names.json   --cam_eval_thres 0.15   --work_space output_refer/refcocog_umd   --num_workers 8   --irn_batch_size 96   --cam_to_ir_label_pass True   --train_irn_pass True   --make_ins_seg_pass True 

error: No such file or directory: '../output/refcocog_umd/refcocog_train_names.json'

**Comment by fawnliu** [comment]
Hi, @RDXiaoLu. Please make sure the `save_cam=True` and  the argument `args.name_save_dir=../output/refcocog_umd/` in the validation process: https://github.com/fawnliu/TRIS/blob/7d2aa18d087f1e4bebd4cf9d73cb774736990330/validate.py#L376

Then, the name file `refcocog_train_names.json` will be found in the folder `../output/refcocog_umd/`.
