### ISSUE TITLE
ModuleNotFoundError: No module named 'demo_utils'

### ISSUE THREAD

**Issue by DYS919** [fawnliu/TRIS#8]
ModuleNotFoundError: No module named 'demo_utils'
![图片](https://github.com/user-attachments/assets/a201587e-afcd-4bd0-8bd4-eab2cc78e7b9)

**Comment by fawnliu** [comment]
Hi, @DYS919. Please note that we do not use the code in [utils.py](https://github.com/fawnliu/TRIS/blob/main/IRNet/utils.py), and you can ignore this warning to run the the refinement process following the guideline in [readme](https://github.com/fawnliu/TRIS/tree/main?tab=readme-ov-file#training).
