### ISSUE TITLE
Regarding the negative query samples for calibration

### ISSUE THREAD

**Issue by lianxxx** [fawnliu/TRIS#9]
I noticed in Table 5, 3/6/12 negative query samples for a same image were tested, I wonder how these negative query samples were generated. Thank you.

**Comment by fawnliu** [comment]
Hi @lianxxx, we implement the code in L190 - L229 [ReferDataset.py](https://github.com/fawnliu/TRIS/blob/c6666b3b89a31504a23f39710e904e1335e23e91/dataset/ReferDataset.py#L190), please check it for more details.
